### ISSUE TITLE
Processing Multiple Exchange BLG files

### ISSUE THREAD

**Issue by kbrussel** [clinthuffman/PAL#1]
Hi-
I'm running PAL 2.7.7 (got it from CodePlex).  When I try to run multiple files through PAL, it seems to crash out.  What am I doing wrong?

PAL.log shows:
**********************
Windows PowerShell transcript start
Start time: 20170517075342
Username: domain\me
RunAs User: domain\me
Machine: 121100 (Microsoft Windows NT 10.0.14393.0)
Host Application: Powershell -ExecutionPolicy ByPass -NoProfile -File .\PAL.ps1 -Log C:\USEIMAIL1303\USEIMAIL13031.blg;C:\USEIMAIL1303\USEIMAIL13032.blg -ThresholdFile C:\Program Files\PAL\PAL\Exchange2013.xml -Interval AUTO -IsOutputHtml $True -HtmlOutputFileName [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].htm -IsOutputXml $False -XmlOutputFileName [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].xml -AllCounterStats $False -NumberOfThreads 4 -IsLowPriority $True -OS 64-bit Windows Server 2012 -PhysicalMemory 64 -UserVa 2048
Process ID: 7728
PSVersion: 5.1.14393.953
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.953
BuildVersion: 10.0.14393.953
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\me\AppData\Local\Temp\PAL.log
PAL 2.7.7 (http://pal.codeplex.com)
Written by: Clint Huffman (clinth@microsoft.com) and other contributors.
Last Modified: 10/27/2016 16:57:48
The information and actions by this tool is provided "as is" and is intended for information purposes only. The authors and contributors of this tool take no responsibility for damages or losses incurred by use of this tool.
Your locale is set to: English (United States)
SCRIPT ARGUMENTS:

Name                           Value
----                           -----
AllCounterStats                False
AnalysisInterval               AUTO
BeginTime
DisplayReport                  True
EndTime
HtmlOutputFileName             [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].htm
Interval                       AUTO
IsLowPriority                  True
IsOutputHtml                   True
IsOutputXml                    False
Log                            C:\MAIL1303\MAIL13031.blg;C:\MAIL1303\MAIL13032.blg
NumberOfThreads                4
OS                             64-bit Windows Server 2012
OutputDir                      [My Documents]\PAL Reports
PhysicalMemory                 64
ThresholdFile                  C:\Program Files\PAL\PAL\Exchange2013.xml
UserVa                         2048
XmlOutputFileName              [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].xml

Creating session working directory...
Creating directory "C:\Users\me\AppData\Local\Temp\6ed36dc0-7bfc-42c4-8b91-63ecc361862a"
Creating file "C:\Users\me\Documents\PAL Reports\MAIL13031_PAL_ANALYSIS_20170517075342.htm"
Creating directory "C:\Users\me\Documents\PAL Reports\MAIL13031_PAL_ANALYSIS_20170517075342\"

Threshold File Load History (in order of priority):
C:\Program Files\PAL\PAL\Exchange2013.xml
SystemOverview.xml
QuickSystemOverview.xml

Generating the counter list to filter on...
Done
Removing duplicate counter expressions from counter list...
Done

PS>TerminatingError(): "The property 'CounterListFilePath' cannot be found on this object. Verify that the property exists."
>> TerminatingError(): "The property 'CounterListFilePath' cannot be found on this object. Verify that the property exists."
The property 'CounterListFilePath' cannot be found on this object. Verify that the property exists.
At C:\Program Files\PAL\PAL\PAL.ps1:1143 char:76
+ ... `"" + ' -cf ' + "`"$($global:oPal.Session.CounterListFilePath)`"" + ' ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
The property 'CounterListFilePath' cannot be found on this object. Verify that the property exists.
At C:\Program Files\PAL\PAL\PAL.ps1:1143 char:76
+ ... `"" + ' -cf ' + "`"$($global:oPal.Session.CounterListFilePath)`"" + ' ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Get-Content : Cannot find path 
'C:\Users\me\AppData\Local\Temp\6ed36dc0-7bfc-42c4-8b91-63ecc361862a\_FilteredPerfmonLog.csv' because it does not 
exist.
At C:\Program Files\PAL\PAL\PAL.ps1:1907 char:14
+     $oCSVFile = Get-Content $CsvFilePath
+                 ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\kbruss...dPerfmonLog.csv:String) [Get-Content], 
ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
Get-Content : Cannot find path
'C:\Users\me\AppData\Local\Temp\6ed36dc0-7bfc-42c4-8b91-63ecc361862a\_FilteredPerfmonLog.csv' because it does
not exist.
At C:\Program Files\PAL\PAL\PAL.ps1:1907 char:14
+     $oCSVFile = Get-Content $CsvFilePath
+                 ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\kbruss...dPerfmonLog.csv:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

PS>TerminatingError(): "Cannot index into a null array."
>> TerminatingError(): "Cannot index into a null array."
Cannot index into a null array.
At C:\Program Files\PAL\PAL\PAL.ps1:1908 char:2
+     $aRawCounterList = $oCSVFile[0].Split(",")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
Cannot index into a null array.
At C:\Program Files\PAL\PAL\PAL.ps1:1908 char:2
+     $aRawCounterList = $oCSVFile[0].Split(",")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Auto analysis interval (one time only)...
PS>TerminatingError(): "Cannot convert null to type "System.DateTime"."
>> TerminatingError(): "Cannot convert null to type "System.DateTime"."
Cannot convert null to type "System.DateTime".
At C:\Program Files\PAL\PAL\PAL.ps1:1929 char:9
+         [datetime] $dtBeginDateTime = $dtBeginDateTime
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException
Cannot convert null to type "System.DateTime".
At C:\Program Files\PAL\PAL\PAL.ps1:1929 char:9
+         [datetime] $dtBeginDateTime = $dtBeginDateTime
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException

Number Of Counter Instances In Perfmon Log: 0

Quantized index (one time only)...
PS>TerminatingError(): "Cannot convert null to type "System.DateTime"."
Cannot convert null to type "System.DateTime".
At C:\Program Files\PAL\PAL\PAL.ps1:2324 char:2
+     [datetime] $dTimeCursor = [datetime] $ArrayOfTimes[0]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : nullToObjectInvalidCast
Cannot convert null to type "System.DateTime".
At C:\Program Files\PAL\PAL\PAL.ps1:2324 char:2
+     [datetime] $dTimeCursor = [datetime] $ArrayOfTimes[0]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : nullToObjectInvalidCast

Matching counter instances to threshold data sources...
Done [1.058 seconds]
Calculating counter statistics [very CPU intensive]...
	Number of jobs passed into Thread(0): 0
	Number of jobs passed into Thread(1): 0
	Number of jobs passed into Thread(2): 0
	Number of jobs passed into Thread(3): 0
PS>TerminatingError(): "Attempted to divide by zero."
Attempted to divide by zero.
At C:\Program Files\PAL\PAL\PAL.ps1:2293 char:49
+ ... ete = ConvertToDataType $(($iIndexOfJobs / $iTotalJobs) * 100) 'integ ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException
Attempted to divide by zero.
At C:\Program Files\PAL\PAL\PAL.ps1:2293 char:49
+ ... ete = ConvertToDataType $(($iIndexOfJobs / $iTotalJobs) * 100) 'integ ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

Creating generated counter data [This is PAL working with multiple counters to produce a single result]...
Creating generated counter data... Done! [1.469 seconds]
Generating Charts...
Processing Thresholds...
Generating the HTML Report...
PS>TerminatingError(): "Cannot convert null to type "System.DateTime"."
>> TerminatingError(): "Cannot convert null to type "System.DateTime"."
Cannot convert null to type "System.DateTime".
At C:\Program Files\PAL\PAL\PAL.ps1:4502 char:25
+     $Date1 = Get-Date $([datetime]$global:oPal.aTime[0]) -format $glo ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : nullToObjectInvalidCast
Cannot convert null to type "System.DateTime".
At C:\Program Files\PAL\PAL\PAL.ps1:4502 char:25
+     $Date1 = Get-Date $([datetime]$global:oPal.aTime[0]) -format $glo ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : nullToObjectInvalidCast

C:\Users\me\Documents\PAL Reports\MAIL13031_PAL_ANALYSIS_20170517075342.htm
**********************
Windows PowerShell transcript end
End time: 20170517075420
**********************

**Comment by clinthuffman** [comment]
Merging log files is can produce unpredictable results and I can’t give you any confidence that it can be parsed by PAL. I’m using relog.exe which is part of the operating system to do the merge. Alternatively, you could convert the counter logs into CSV and manually merge them together – it might help.
