### ISSUE TITLE
Question about PAL tool.

### ISSUE THREAD

**Issue by mkruzel** [clinthuffman/PAL#10]
I'm trying the PAL tool for the first time and it works great. I'm looking in the .html document and see this pc - zach-pc Is this just the pc that was the counters were created on? Or can you enter the pc name in the program? Also, is there a Windows 10 version coming?

The Windows Performance Analysis Field Guide is a fantastic book. Thank you.

**Comment by jeffstokes72** [comment]
@mkruzel howdy, are you talking about reviewing the results html?

I think I understand the question. The name is read from the perfmon blg, it's a field in the collection.

@clinthuffman is working on a v3 of PAL I am told.

**Comment by mkruzel** [comment]
Yes, I'm talking about the .html document.    Thank you!

**Comment by jeffstokes72** [comment]
@mkruzel pro-tip, you can relog the host name into something else before making your PAL reports :)

**Comment by clinthuffman** [comment]
It sounds like you are analyzing the performance counter log that ships with the tool for basic functionality testing. ZACH-PC is the name of the computer in that counter log. In your case, you need to analyze the performance counter log that you have either a *.blg for *.csv performance counter log.
