### ISSUE TITLE
Divide by zero 

### ISSUE THREAD

**Issue by bremyk** [clinthuffman/PAL#11]
Overall progress... Status: Calculating counter statistics [very CPU intensive]..., PAL 2.7.7 Progress: 65%... Calculating counter statistics [very CPU intensive]..., 

An error occurred on...
$iPercentComplete = ConvertToDataType $(($iIndexOfJobs / $iTotalJobs) * 100) 'integer' 
At C:\PerfLogs\PAL_FlatFiles_2.7.7_x64\PAL.ps1:2293 char:49 + ... ete = ConvertToDataType $(($iIndexOfJobs / $iTotalJobs) * 100) 'integ ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Attempted to divide by zero.

SCRIPT ARGUMENTS:
Log: C:\PerfLogs\551 System Monitor Log.blg
ThresholdFile: C:\Users\user\AppData\Local\Temp\PalAutoDetectThresholdFile_95451b8a-be52-4b0e-a86a-51502b9f8bcb.xml
AnalysisInterval: AUTO
IsOutputHtml: $True
IsOutputXml: $False
HtmlOutputFileName: [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].htm
XmlOutputFileName: [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].xml
OutputDir: [My Documents]\PAL Reports
AllCounterStats: $True
NumberOfThreads: 4
IsLowPriority: $True
DisplayReport: True

**Comment by clinthuffman** [comment]
Try changing the file name to not have spaces in it.

**Comment by bremyk** [comment]
That worked.

**Comment by wasytb** [comment]
Same issue here. No spaces this time:
Overall progress... Status: Calculating counter statistics [very CPU intensive]..., PAL 2.8.2 Progress: 65%... Calculating counter statistics [very CPU intensive]..., 

An error occurred on...
$iPercentComplete = ConvertToDataType $(($iIndexOfJobs / $iTotalJobs) * 100) 'integer' 
At C:\Users\wasytb\Downloads\PAL-LatestVersion\PAL.ps1:2526 char:49 + ... ete = ConvertToDataType $(($iIndexOfJobs / $iTotalJobs) * 100) 'integ ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Attempted to divide by zero.


SCRIPT ARGUMENTS:
Log: C:\Users\wasytb\Downloads\PAL-Reports\SHV-VIRTUA4_57129e6c-fdd0-443c-9191-5c1fa53028ce.blg
ThresholdFile: C:\Users\wasytb\Downloads\PAL-LatestVersion\HyperV30.xml
AnalysisInterval: AUTO
IsOutputHtml: $True
IsOutputXml: $False
HtmlOutputFileName: [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].htm
XmlOutputFileName: [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].xml
OutputDir: C:\Users\wasytb\Documents\PAL-Reports
AllCounterStats: $False
NumberOfThreads: 2
IsLowPriority: $True
DisplayReport: True

**Comment by clinthuffman** [comment]
Can you send me the BLG, so I can debug it? Upload to http://bit.ly/PalUpload
________________________________

**Comment by wasytb** [comment]
Never mind!. Too few samples issue. Thanks Clint!
