### ISSUE TITLE
How do I handle data integrity wrt Time field?

### ISSUE THREAD

**Issue by jeffstokes72** [clinthuffman/PAL#14]
Let us suppose someone relogged a blg file and in an effort to remove PII, mangled the date field. Is there a way to just tell PAL to process "from 0 time to end of time" since in the BLG/csv it does increment the hour value?

**Comment by clinthuffman** [comment]
That *should* work still so long as the date-time fields are relatively coherent.
The harder challenge is to compare the same performance counter from counter logs from different time ranges. It would have to be relative say from 0, 1, 2, 3 minutes, and so on. This would be a good feature for PAL Pro which is currently in development.

**Comment by jeffstokes72** [comment]
Can I help with the pro version?
:)

**Comment by clinthuffman** [comment]
Yes, I would be honored to have your help, but let's take this offline via email.
