### ISSUE TITLE
Can not convert value during data processing

### ISSUE THREAD

**Issue by jonsey80** [clinthuffman/PAL#18]
Recreating: converting a 60 mins perfmon file with multiple system and SQL counters using the all threashold File title on Pal v2.7.7

when it started processing Edge Transport - physical Disk avg.disk sec/reads the error was thrown

Invoke-Expression : Could not compare "0" to "0.02". Error: "Cannot convert value "0.02" to type "System.Char". Error:
"Invalid cast from 'Double' to 'Char'.""
At C:\Program Files\PAL\PAL\PAL.ps1:4337 char:9
+         Invoke-Expression -Command $sCode
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Expression], RuntimeException
    + FullyQualifiedErrorId : ComparisonFailure,Microsoft.PowerShell.Commands.InvokeExpressionCommand

From the HTML Report:

Overall progress... Status: Applying thresholds, PAL 2.7.7 Progress: 82%... Applying thresholds, Edge Transport - PhysicalDisk Avg. Disk sec/Read 

 An error occurred on...
	If ($oCounterInstance.QuantizedAvg[$t] -ge 0.02) 
At line:11 char:7 + If ($oCounterInstance.QuantizedAvg[$t] -ge 0.02) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not compare "0" to "0.02". Error: "Cannot convert value "0.02" to type "System.Char". Error: "Invalid cast from 'Double' to 'Char'.""

 SCRIPT ARGUMENTS:
 Log: C:\Users\mark.jones\Documents\ledw_etl\DBEDWSTGP1_DataCollector01.blg
 ThresholdFile: C:\Program Files\PAL\PAL\All.xml
 AnalysisInterval: AUTO
 IsOutputHtml: $True
 IsOutputXml: $False
 HtmlOutputFileName: [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].htm
 XmlOutputFileName: [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].xml
 OutputDir: C:\Users\mark.jones\Documents\ledw_etl\preissue
 AllCounterStats: $False
 NumberOfThreads: 4
 IsLowPriority: $True
 DisplayReport: True

Please contact the PAL tool team with this error by posting it to pal.codeplex.com. Thank you!

from the pal log 

 Edge Transport - PhysicalDisk Avg. Disk sec/Read
PS>TerminatingError(Invoke-Expression): "Could not compare "0" to "0.02". Error: "Cannot convert value "0.02" to type "System.Char". Error: "Invalid cast from 'Double' to 'Char'."""
>> TerminatingError(Invoke-Expression): "Could not compare "0" to "0.02". Error: "Cannot convert value "0.02" to type "System.Char". Error: "Invalid cast from 'Double' to 'Char'."""
>> TerminatingError(Invoke-Expression): "Could not compare "0" to "0.02". Error: "Cannot convert value "0.02" to type "System.Char". Error: "Invalid cast from 'Double' to 'Char'."""
>> TerminatingError(Invoke-Expression): "Could not compare "0" to "0.02". Error: "Cannot convert value "0.02" to type "System.Char". Error: "Invalid cast from 'Double' to 'Char'."""
Invoke-Expression : Could not compare "0" to "0.02". Error: "Cannot convert value "0.02" to type "System.Char". Error: 
"Invalid cast from 'Double' to 'Char'.""
At C:\Program Files\PAL\PAL\PAL.ps1:4337 char:9
+         Invoke-Expression -Command $sCode
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Expression], RuntimeException
    + FullyQualifiedErrorId : ComparisonFailure,Microsoft.PowerShell.Commands.InvokeExpressionCommand
Invoke-Expression : Could not compare "0" to "0.02". Error: "Cannot convert value "0.02" to type "System.Char". Error:
"Invalid cast from 'Double' to 'Char'.""
At C:\Program Files\PAL\PAL\PAL.ps1:4337 char:9
+         Invoke-Expression -Command $sCode
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Expression], RuntimeException
    + FullyQualifiedErrorId : ComparisonFailure,Microsoft.PowerShell.Commands.InvokeExpressionCommand

Generating the HTML Report...

**Comment by clinthuffman** [comment]
The All threshold file wasn’t tested and I probably shouldn’t have released it. If you are XML savvy, try disabling the “Edge Transport - physical Disk avg.disk sec/reads” analysis node by setting Enabled=”False” and try again. Processing of multiple counter logs can have unexpected results because PAL uses relog.exe to do the merging. If disabling the analysis node doesn’t work, then I recommend analyzing each counter log individually.
