### ISSUE TITLE
Property 'CounterComputer' cannot be found on this object. Make sure that it exists.

### ISSUE THREAD

**Issue by plykkegaard** [clinthuffman/PAL#2]
Log generated on Windows 2012 / BizTalk 2013, standard PAL BizTalk template used in Performance Monitor
-------------------------------------------------------------
Overall progress... Status: Generating analysis counters, PAL 2.7.7 Progress: 71%... Generating analysis counters, BizTalk Orchestrations Resident in Memory 

 An error occurred on...
 $sInstanceNameForXLANGsOrchestrationsDehydratableorchestrationsALLWithComputer = "$($htVariables["CollectionOfXLANGsOrchestrationsDehydratableorchestrationsALL"][$a].CounterComputer)" + '/' + "$($htVariables["CollectionOfXLANGsOrchestrationsDehydratableorchestrationsALL"][$a].CounterInstance)" 
At line:10 char:99 + $sInstanceNameForXLANGsOrchestrationsDehydratableorchestrationsALL ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Property 'CounterComputer' cannot be found on this object. Make sure that it exists.

 SCRIPT ARGUMENTS:
 Log: ---_20170605-000002\PAL_Microsoft_BizTalk_Server_2006_2009_2010.blg
 ThresholdFile: ---\BizTalkServer2006.xml
 AnalysisInterval: AUTO
 IsOutputHtml: $True
 IsOutputXml: $False
 HtmlOutputFileName: [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].htm
 XmlOutputFileName: [LogFileName]_PAL_ANALYSIS_[DateTimeStamp].xml
 OutputDir: [My Documents]\PAL Reports
 AllCounterStats: $False
 NumberOfThreads: 4
 IsLowPriority: $True
 DisplayReport: True

**Comment by plykkegaard** [comment]
Same process:

The variable '$CollectionOfNetworkUtilization' cannot be retrieved because it has not been set.

**Comment by clinthuffman** [comment]
Can you send me the BLG counter log, so I can debug this? Please upload to https://1drv.ms/f/s!AhuJirRUDDbmqw17QAt9UjDBxSKO

**Comment by plykkegaard** [comment]
Only option is download on the page, dragging the file in does not work
It's 740 Mb

**Comment by clinthuffman** [comment]
Oh, okay. Try this one https://1drv.ms/f/s!AhuJirRUDDbmqw19Lxlj-8JF4fe7

**Comment by plykkegaard** [comment]
Works, had to cancel it though, I'll upload tomorrow first thing

**Comment by plykkegaard** [comment]
PAL_Microsoft_BizTalk_Server_2006_2009_2010.blg uploaded

4 threads, Low priority

Parameters
--------------------
Powershell -ExecutionPolicy ByPass -NoProfile -File ".\PAL.ps1"
-Log "----------------------------------------\PAL_Microsoft_BizTalk_Server_2006_2009_2010.blg"
-ThresholdFile "C:\Program Files\PAL\PAL\BizTalkServer2006.xml"
-Interval "1800"
-IsOutputHtml $True
-HtmlOutputFileName "[LogFileName]_PAL_ANALYSIS_[DateTimeStamp].htm"
-IsOutputXml $False
-XmlOutputFileName "[LogFileName]_PAL_ANALYSIS_[DateTimeStamp].xml"
-AllCounterStats $False
-NumberOfThreads 4
-IsLowPriority $True
-OS "64-bit Windows Server 2012"
-PhysicalMemory "12"
-UserVa "2048"

**Comment by plykkegaard** [comment]
Had two runs without issues but dump from yesterday had the same problem as reported
Might be due to my system more than a general problem?

Thanks

**Comment by clinthuffman** [comment]
Okay, please upload and reopen this issue if it still occurs. Thank you.
