### ISSUE TITLE
Perfmon Log Translator

### ISSUE THREAD

**Issue by Chemaister** [clinthuffman/PAL#21]
Hi,

I'm having some problems related to the language on the system. Looking at old codeplex I found people use to solve it with PLT but I cannot found it neither in the old nor new sites. Is the tool still available?

**Comment by clinthuffman** [comment]
Go to my personal OneDrive at http://aka.ms/ClintH, then go to the Tools folder. Download the PLT zip file from there.
I have language translation planned in the next major version of PAL.

**Comment by Chemaister** [comment]
Hi Clint,

Awesome, thanks! I'm still not proficient with powershell but for what is worth I can give support on testing next PAL for spanish.

Thanks!

**Comment by clinthuffman** [comment]
Thanks. Yes, Spanish is the most commonly requested language. Thanks, but I already have full translation of most of the OS counters. The reports would be the only thing to have translated at this point.
