### ISSUE TITLE
Hi, i've been working on an older version, to manage french language / code updating.

### ISSUE THREAD

**Issue by babatman** [clinthuffman/PAL#24]
Here the functions i used to it 

Function Set-FrenchLocales
{
    param()
    $global:originalCulture = (Get-Culture)
    $usenglishLocales = new-object System.Globalization.CultureInfo "fr-FR"   
    $global:currentThread.CurrentCulture = $usenglishLocales
    $global:currentThread.CurrentUICulture = $usenglishLocales
}

Function GlobalizationCheck
{
    $sDisplayName = (Get-Culture).DisplayName
	Write-Host "Your locale is set to: $sDisplayName"
	$global:currentThread = [System.Threading.Thread]::CurrentThread
	If ($($sDisplayName.Contains('English')) -eq $false)
	{
        if($sDisplayName.Contains('France')){
            $global:bEnglishLocale = $false
            Write-Host 'Your locale is not English. PAL unfortunately must be running under an English locale. Setting it to English-US.'
            Set-FrenchLocales
        }
        else{
            $global:bEnglishLocale = $false
            Write-Host 'Your locale is not English. PAL unfortunately must be running under an English locale. Setting it to English-US.'
            Set-EnglishLocales
        }
	}
    Else
    {
        $global:bEnglishLocale = $true
    }
}
Function ReadThresholdFileIntoMemory
{
	param($sThresholdFilePath)	
	[xml] (Get-Content $sThresholdFilePath -Encoding UTF8)	
}
Function InheritFromThresholdFiles
{
    param($sThresholdFilePath)
    
    $XmlThresholdFile = [xml] (Get-Content $sThresholdFilePath -Encoding UTF8)
    CheckPalXmlThresholdFileVersion -XmlThresholdFile $XmlThresholdFile
    #// Add it to the threshold file load history, so that we don't get into an endless loop of inheritance.
    If ($global:oXml.ThresholdFilePathLoadHistory.Contains($sThresholdFilePath) -eq $False)
    {
        [void] $global:oXml.ThresholdFilePathLoadHistory.Add($sThresholdFilePath)
    }
    
    #// Inherit from other threshold files.
    ForEach ($XmlInheritance in $XmlThresholdFile.SelectNodes('//INHERITANCE'))
    {
        If ($(Test-FileExists $XmlInheritance.FilePath) -eq $True)
        {
            $XmlInherited = [xml] (Get-Content $XmlInheritance.FilePath -Encoding UTF8)
            ForEach ($XmlInheritedAnalysisNode in $XmlInherited.selectNodes('//ANALYSIS'))
            {
                $bFound = $False            
                ForEach ($XmlAnalysisNode in $global:oXml.XmlAnalyses.SelectNodes('//ANALYSIS'))
                {
                    If (($(Test-property -InputObject $XmlInheritedAnalysisNode -Name 'ID') -eq $True) -and ($(Test-property -InputObject $XmlAnalysisNode -Name 'ID') -eq $True))
                    {
                        If ($XmlInheritedAnalysisNode.ID -eq $XmlAnalysisNode.ID)
                        {
                            $bFound = $True
                            Break
                        }
                    }

                    If ($XmlInheritedAnalysisNode.NAME -eq $XmlAnalysisNode.NAME)
                    {
                        $bFound = $True
                        Break
                    }
                }
                If ($bFound -eq $False)
                {
                    [void] $global:oXml.XmlAnalyses.AppendChild($global:oXml.XmlRoot.ImportNode($XmlInheritedAnalysisNode, $True))
                }
            }
            ForEach ($XmlInheritedQuestionNode in $XmlInherited.selectNodes("//QUESTION"))
            {
                $bFound = $False
                ForEach ($XmlQuestionNode in $global:oXml.XmlAnalyses.selectNodes("//QUESTION"))
                {
                    If ($XmlInheritedQuestionNode.QUESTIONVARNAME -eq $XmlQuestionNode.QUESTIONVARNAME)
                    {
                        $bFound = $True
                        Break
                    }
                }
                If ($bFound -eq $False)
                {            
                    [void] $global:oXml.XmlAnalyses.AppendChild($global:oXml.XmlRoot.ImportNode($XmlInheritedQuestionNode, $True))
                }
            }
            
    		If ($global:oXml.ThresholdFilePathLoadHistory.Contains($XmlInheritance.FilePath) -eq $False)
    		{
    			InheritFromThresholdFiles $XmlInheritance.FilePath
    		}
        }
    }
}

Function GenerateThresholdFileCounterList
{
    Write-Host 'Generating the counter list to filter on...' -NoNewline
    $p = $global:oPal.Session.SessionWorkingDirectory + '\CounterListFilter.txt'
    $c = New-Object System.Collections.ArrayList
    ForEach ($XmlAnalysisInstance in $global:oXml.XmlAnalyses.SelectNodes('//ANALYSIS'))
    {
        If ($(ConvertTextTrueFalse $XmlAnalysisInstance.ENABLED) -eq $True)
        {
            ForEach ($XmlAnalysisDataSourceInstance in $XmlAnalysisInstance.SelectNodes('./DATASOURCE'))
            {
                If ($XmlAnalysisDataSourceInstance.TYPE -eq 'CounterLog')
                {
                    If ($(Test-property -InputObject $XmlAnalysisDataSourceInstance -Name 'ISCOUNTEROBJECTREGULAREXPRESSION') -eq $True)
                    {
                        If ($(ConvertTextTrueFalse $XmlAnalysisDataSourceInstance.ISCOUNTEROBJECTREGULAREXPRESSION) -eq $True)
                        {
                            $oCtr = CounterPathToObject -sCounterPath $XmlAnalysisDataSourceInstance.EXPRESSIONPATH
                            If ($($oCtr.Instance) -eq $null)
                            {
                                $sNewExpressionPath = '\' + '*' + '\' + "$($oCtr.Name)"
                            }
                            Else
                            {
                                $sNewExpressionPath = '\' + '*' + '(' + "$($oCtr.Instance)" + ')\' + "$($oCtr.Name)"
                            }
                            $c += $sNewExpressionPath
                        }
                        Else
                        {
                            $c += $XmlAnalysisDataSourceInstance.EXPRESSIONPATH
                        }
                    }
                    Else
                    {
                        $c += $XmlAnalysisDataSourceInstance.EXPRESSIONPATH
                    }
                }
            }
        }
    }
    Write-Host 'Done'
    Write-Host 'Removing duplicate counter expressions from counter list...' -NoNewline
    #// Remove duplicate counter expression paths
    $c = $c | select -uniq
    $c | Out-File -FilePath $p -Encoding utf8
    $global:oPal.Session.CounterListFilterFilePath = $p
    Write-Host 'Done'
    Write-Host ''
}
Function MergeConvertFilterPerfmonLogs
{
    param($sPerfmonLogPaths, $BeginTime=$null, $EndTime=$null)
    $sCommand = ''
    $RelogOutput = ''
    $IsSingleCsvFile = CheckIsSingleCsvFile -sPerfmonLogPaths $sPerfmonLogPaths
	$global:oPal.RelogedLogFilePath = $global:oPal.Session.SessionWorkingDirectory + "\_FilteredPerfmonLog.csv"
    $global:sFirstCounterLogFilePath = $sPerfmonLogPaths

	If ($IsSingleCsvFile -eq $False)
	{
		$sTemp = ''
		If ($sPerfmonLogPaths.Contains(';'))
		{
			$aPerfmonLogPaths = $sPerfmonLogPaths.Split(';')
            $global:sFirstCounterLogFilePath = $aPerfmonLogPaths[0]
			For ($f=0;$f -lt $aPerfmonLogPaths.length;$f++)
			{
				$sTemp = $sTemp + " " + "`"" + $aPerfmonLogPaths[$f] + "`""
			}
			$sTemp = $sTemp.Trim()

            If ($global:oPal.ArgsProcessed.AllCounterStats -eq $True)
            {
                $sCommand = $('relog.exe ' + "`"$sTemp`"" + ' -f csv -o ' + "`"$($global:oPal.RelogedLogFilePath)`"")
                $outputLogFileANSIToUTF8 = $global:oPal.RelogedLogFilePath
            }
            Else
            {
                $sCommand = $('relog.exe ' + "`"$sTemp`"" + ' -cf ' + "`"$($global:oPal.Session.CounterListFilePath)`"" + ' -f csv -o ' + "`"$($global:oPal.RelogedLogFilePath)`"")
                $outputLogFileANSIToUTF8 = $global:oPal.Session.CounterListFilePath
                }
		}
		Else
		{
            $global:sFirstCounterLogFilePath = $sPerfmonLogPaths
            If ($global:oPal.ArgsProcessed.AllCounterStats -eq $True)
            {
                $sCommand = $('relog.exe ' + "`"$sPerfmonLogPaths`"" + ' -f csv -o ' + "`"$($global:oPal.RelogedLogFilePath)`"" + ' -y')
                $outputLogFileANSIToUTF8 = $global:oPal.RelogedLogFilePath
            }
            Else
            {
                $sCommand = 'relog.exe ' + "`"$sPerfmonLogPaths`"" + ' -cf ' + "`"$($global:oPal.Session.CounterListFilterFilePath)`"" + ' -f csv -o ' + "`"$($global:oPal.RelogedLogFilePath)`"" + ' -y'
                $outputLogFileANSIToUTF8 = $global:oPal.Session.CounterListFilePath
            }
		}
	}
	Else
	{
        #// Just use the original CSV perfmon log.
        $global:oPal.RelogedLogFilePath = $sPerfmonLogPaths
        $global:sFirstCounterLogFilePath = $sPerfmonLogPaths
	}
    
    If (($global:oPal.ArgsProcessed.BeginTime -ne $null) -and ($global:oPal.ArgsProcessed.EndTime -ne $null))
    {
        #// Fix provided by kwomba
        $sCommand = "$sCommand" + ' -b ' + "`"$($global:oPal.ArgsProcessed.BeginTime)`"" + ' -e ' + "`"$($global:oPal.ArgsProcessed.EndTime)`""
    }
    
    If ($IsSingleCsvFile -eq $False)
    {
        Write-Host $sCommand
        Write-Host ''
        $RelogOutput = Invoke-Expression -Command $sCommand

        $tmpToDelete = $oPal.Session.UserTempDirectory + '\' + ([System.GUID]::NewGUID()).guid
        get-content $outputLogFileANSIToUTF8  | set-content $tmpToDelete -Encoding UTF8
        copy-item $tmpToDelete -destination  $outputLogFileANSIToUTF8
        #// Remove the extra blank lines and relog progress bar.
        Remove-Item $tmpToDelete -Force
        $RelogOutput | ForEach-Object {If (($_ -ne '') -and ($_.SubString(0,1) -ne 0)) {$_}}
    }
    
    $sRelogOutputAsSingleString = [string]::join("", $RelogOutput)
    If ($sRelogOutputAsSingleString.contains('No data to return.') -eq $True)
    {
        
        $sError = "Relog.exe failed to process the log. This commonly occurs when a BLG file from a Windows Vista or newer operating system is attempting to be analyze on Windows XP or Windows Server 2003, or due to log corruption. If you see this message on Windows XP or Server 2003, then try analyzing the log on Windows Vista/Server 2008 or later. Review the results above this line. If relog.exe continues to fail, then try running Relog.exe manually and/or contact Microsoft Customer Support Servers for support on Relog.exe only. PAL is not supported by Microsoft."
        WriteErrorToHtmlAndShow -sError $sError
        Break Main
    }
    
	$NewLogExists = Test-Path -Path $global:oPal.RelogedLogFilePath
	If ($NewLogExists -eq $False)
	{	
		$sError = $('[MergeConvertFilterPerfmonLogs] ERROR: Unable to find the converted log file: ' + "$($global:oPal.RelogedLogFilePath). " + "Relog.exe failed to process the log. Review the results above this line. If relog.exe continues to fail, then try running Relog.exe manually and/or contact Microsoft Customer Support Servers for support on Relog.exe only. PAL is not supported by Microsoft.")
        WriteErrorToHtmlAndShow -sError $sError
        Write-Error $sError
		Break Main
	}

    If (($IsSingleCsvFile -eq $False) -and ($RelogOutput -ne $null))
    {
        If ($(IsSamplesInPerfmonLog -RelogOutput $RelogOutput) -eq $False)
        {
    		$sError = $("[MergeConvertFilterPerfmonLogs] ERROR: Unable to use the log file(s): " + "$($global:oPal.ArgsOriginal.Log). " + "The counters in the log(s) do not contain any useable samples.")
            WriteErrorToHtmlAndShow -sError $sError
            Write-Error $sError
    		Break Main
        }
    }
    If ($RelogOutput -ne $null)
    {
        $NumberOfSamples = GetNumberOfSamplesFromRelogOutput -sRelogOutput $RelogOutput
        If ($NumberOfSamples -is [System.Int32])
        {
            If ($NumberOfSamples -lt 10)
            {
                $sText = $("ERROR: Not enough samples in the counter log to properly process. Create another performance counter log with more samples in it and try again. Number of samples is: " + "$NumberOfSamples")
                Write-Error $sText
                WriteErrorToHtmlAndShow -sError $sText
                Break Main
            }
        }
    }
}
Function ConstructCounterDataArray
{
    $PercentComplete = 0
    $sComplete = "Progress: 0% (Counter ?? of ??)"
    write-progress -activity 'Importing counter data into memory...' -status $sComplete -percentcomplete $PercentComplete -id 2
    
	$oCSVFile = Get-Content -Path $global:oPal.RelogedLogFilePath -Encoding UTF8
	#// Get the width and height of the CSV file as indexes.
	$aLine = $oCSVFile[0].Trim('"') -split '","'
    $iPerfmonCsvIndexWidth = $aLine.GetUpperBound(0)
	$iPerfmonCsvIndexHeight = $oCSVFile.GetUpperBound(0)

	If ($($oCSVFile[$iPerfmonCsvIndexHeight].Contains(',')) -eq $False)
	{
		do 
		{
			$iPerfmonCsvIndexHeight = $iPerfmonCsvIndexHeight - 1
		} until ($($oCSVFile[$iPerfmonCsvIndexHeight].Contains(',')) -eq $true)	
	}
	For ($i=0;$i -le $iPerfmonCsvIndexHeight;$i++)
	{
		$aLine = $oCSVFile[$i].Trim('"') -split '","'
		[void] $global:oPal.LogCounterData.Add($aLine)
        $PercentComplete = CalculatePercentage -Number $i -Total $iPerfmonCsvIndexHeight
        $sComplete = "Progress: $(ConvertToDataType $PercentComplete 'integer')% (Counter $i of $iPerfmonCsvIndexHeight)"
        write-progress -activity 'Importing counter data into memory...' -status $sComplete -percentcomplete $PercentComplete -id 2
	}
    $sComplete = "Progress: 100% (Counter $iPerfmonCsvIndexHeight of $iPerfmonCsvIndexHeight)"
    write-progress -activity 'Importing counter data into memory...' -status $sComplete -Completed -id 2
}
Function GetTimeZoneFromCsvFile
{
    param($CsvFilePath)
    
	$oCSVFile = Get-Content $CsvFilePath -Encoding UTF8
	$aRawCounterList = $oCSVFile[0].Split(",")
	Return $aRawCounterList[0].Trim("`"")
}

**Comment by babatman** [comment]
Hey,

Yes it is.
I had the problem to get the good encoding of my file, so i have to use a
temp file (not great) but it's working (and all the rest).

I've been working with perfs counter (with zabbix supervision), i use the
number representation of counter. I don't remember PAL code and the way
you're doing the stuff  (i've done that many months ago) but it could be
useful.

In \HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\
009 English
00C >> for my computer / french
[image: image.png]
[image: image.png]

It contains current language and english language, so an easy way to handle
things would be to make a mapping array with perf counter number & name
English & local (for me french)
Anyway, thank you for good job!


Le mar. 11 sept. 2018 à 20:24, Clint Huffman <notifications@github.com> a
écrit :

**Comment by clinthuffman** [comment]
Thanks, but I just so happen to have all of the operating system counters translated to 16 languages now. 😊 Unfortunately, the Perflib registry key looked very promising, but it doesn’t have the full path of the counters and was very random with the strings – only partial counter paths here and there. With that said, your logic on translating the counters by index number is what I ended up doing, but with a different source.

I installed each language pack on Windows Server 2016, I logged on with each language, and then I had a log on script that automatically ran typeperf -q into a text file. Most of the counters literally “lined up” where line number 100 was the same counter for each language in each respective file. This worked out a lot better since it gave me the full paths of the performance counters. It took a lot of work to synchronize the files and then merge them all into a single XML file, but I feel very happy to get it done finally.

PAL 2.8 (beta)( https://github.com/clinthuffman/PAL/blob/master/PAL_2.8-Beta.zip?raw=true) has the counter log translations in it. If you have a counter log recorded in French or any of the 16 languages that I now support, then please try it out and let me know if it works properly.

Now, the other problem is that the PAL.ps1 powershell script still needs to have the locale set to English in order to execute. If I remember correctly, the only reason I required it was because of the counter comparisons, but now that I got that added, I think it should be relatively easy to allow any locale to run it.

Also, I am planning to do a new round of threshold files for the latest Microsoft server products soon… with language translation support as well. But, it will be a *lot* of work, so I plan to sell these “PAL Pro Packs” early next year.

Thanks for all of the feedback. I do appreciate it.

Thank you,


________________________________

**Comment by clinthuffman** [comment]
Fixed in PAL 2.8.0. Please try this version and reopen this issue if the problem still persists.

**Comment by babatman** [comment]
Hey,

Thank you for emailing me with this great news!! Good job!! :)

Le lun. 21 janv. 2019 à 22:12, Clint Huffman <notifications@github.com> a
écrit :
