### ISSUE TITLE
SQL 2014 XML template does not collect any SQL counters 

### ISSUE THREAD

**Issue by bulentozkir** [clinthuffman/PAL#25]
SQL 2014 template does not any SQL counters. It only collects Windows counters. The XML file seems incorrect. Regards.

**Comment by jeffstokes72** [comment]
Do you use a SQL Instance name? If so did you fill it in?

**Comment by jeffstokes72** [comment]
![image](https://user-images.githubusercontent.com/9102841/46070348-90274200-c14b-11e8-8eed-09e0273c9178.png)

**Comment by jeffstokes72** [comment]
or @bulentozkir do you think this is all related to https://github.com/clinthuffman/PAL/issues/26 ?

**Comment by bulentozkir** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/9102841/46070348-90274200-c14b-11e8-8eed-09e0273c9178.png)

I am not using any named instance. Just using the default instance. Therefore I leave it empty. 

I tested the default SQL 2014 XML template on several different machines. They don't match the naming of the SQL perfmon counters somehow. Therefore counter names need to be corrected for SQL 2014, SQL 2016, SQL 2017 etc. 

<Counter>\SQLAgent:Jobs\Active jobs</Counter>
    <Counter>\SQLAgent:Jobs\Failed jobs</Counter>
    <Counter>\SQLAgent:Jobs\Job success rate</Counter>
    <Counter>\SQLAgent:Jobs\Successful jobs</Counter>
    <Counter>\SQLAgent:JobSteps\Active steps</Counter>
    <Counter>\SQLAgent:JobSteps\Total step retries</Counter>
    <Counter>\SQLServer:Access Methods\Forwarded Records/sec</Counter>
    <Counter>\SQLServer:Access Methods\FreeSpace Scans/sec</Counter>
    <Counter>\SQLServer:Access Methods\Full Scans/sec</Counter>
    <Counter>\SQLServer:Access Methods\Index Searches/sec</Counter>
    <Counter>\SQLServer:Access Methods\Page Splits/sec</Counter>
    <Counter>\SQLServer:Access Methods\Scan Point Revalidations/sec</Counter>
    <Counter>\SQLServer:Access Methods\Table Lock Escalations/sec</Counter>
    <Counter>\SQLServer:Access Methods\Workfiles Created/sec</Counter>
    <Counter>\SQLServer:Access Methods\Worktables Created/sec</Counter>
    <Counter>\SQLServer:Access Methods\Worktables From Cache Ratio</Counter>
    <Counter>\SQLServer:Availability Replica(*)\Bytes Received from Replica/sec</Counter>
    <Counter>\SQLServer:Availability Replica(*)\Bytes Sent to Replica/sec</Counter>
    <Counter>\SQLServer:Availability Replica(*)\Bytes Sent to Transport/sec</Counter>
    <Counter>\SQLServer:Availability Replica(_Total)\Receives from Replica/sec</Counter>
    <Counter>\SQLServer:Availability Replica(_Total)\Resent Messages/sec</Counter>
    <Counter>\SQLServer:Availability Replica(_Total)\Sends to Replica/sec</Counter>
    <Counter>\SQLServer:Buffer Manager(*)\Extension page unreferenced time</Counter>
    <Counter>\SQLServer:Buffer Manager\Background writer pages/sec</Counter>
    <Counter>\SQLServer:Buffer Manager\Buffer cache hit ratio</Counter>
    <Counter>\SQLServer:Buffer Manager\Checkpoint pages/sec</Counter>
    <Counter>\SQLServer:Buffer Manager\Extension free pages</Counter>
    <Counter>\SQLServer:Buffer Manager\Extension outstanding IO counter</Counter>
    <Counter>\SQLServer:Buffer Manager\Free list stalls/sec</Counter>
    <Counter>\SQLServer:Buffer Manager\Free pages</Counter>
    <Counter>\SQLServer:Buffer Manager\Lazy writes/sec</Counter>
    <Counter>\SQLServer:Buffer Manager\Page life expectancy</Counter>
    <Counter>\SQLServer:Buffer Manager\Page lookups/sec</Counter>
    <Counter>\SQLServer:Buffer Manager\Page reads/sec</Counter>
    <Counter>\SQLServer:Buffer Manager\Page writes/sec</Counter>
    <Counter>\SQLServer:Buffer Manager\Readahead pages/sec</Counter>
    <Counter>\SQLServer:Buffer Manager\Target pages</Counter>
    <Counter>\SQLServer:Buffer Node(*)\Database pages</Counter>
    <Counter>\SQLServer:Buffer Node(*)\Foreign pages</Counter>
    <Counter>\SQLServer:Buffer Node(*)\Local node page lookups/sec</Counter>
    <Counter>\SQLServer:Buffer Node(*)\Page life expectancy</Counter>
    <Counter>\SQLServer:Buffer Node(*)\Remote node page lookups/sec</Counter>
    <Counter>\SQLServer:Database Replica(*)\Log Bytes Received/sec</Counter>
    <Counter>\SQLServer:Database Replica(*)\Mirrored Write Transactions/sec</Counter>
    <Counter>\SQLServer:Database Replica(*)\Recovery Queue</Counter>
    <Counter>\SQLServer:Database Replica(_Total)\Log remaining for undo</Counter>
    <Counter>\SQLServer:Database Replica(_Total)\Log Send Queue</Counter>
    <Counter>\SQLServer:Database Replica(_Total)\Redo blocked/sec</Counter>
    <Counter>\SQLServer:Database Replica(_Total)\Redo Bytes Remaining</Counter>
    <Counter>\SQLServer:Database Replica(_Total)\Redone Bytes/sec</Counter>
    <Counter>\SQLServer:Database Replica(_Total)\Total Log requiring undo</Counter>
    <Counter>\SQLServer:Database Replica(_Total)\Transaction Delay</Counter>
    <Counter>\SQLServer:Databases(*)\Active Transactions</Counter>
    <Counter>\SQLServer:Databases(*)\Backup/Restore Throughput/sec</Counter>
    <Counter>\SQLServer:Databases(*)\Bulk Copy Throughput/sec</Counter>
    <Counter>\SQLServer:Databases(*)\Data File(s) Size (KB)</Counter>
    <Counter>\SQLServer:Databases(*)\Log Bytes Flushed/sec</Counter>
    <Counter>\SQLServer:Databases(*)\Log File(s) Size (KB)</Counter>
    <Counter>\SQLServer:Databases(*)\Log File(s) Used Size (KB)</Counter>
    <Counter>\SQLServer:Databases(*)\Log Flush Wait Time</Counter>
    <Counter>\SQLServer:Databases(*)\Log Flush Waits/sec</Counter>
    <Counter>\SQLServer:Databases(*)\Log Flushes/sec</Counter>
    <Counter>\SQLServer:Databases(*)\Log Growths</Counter>
    <Counter>\SQLServer:Databases(*)\Log Shrinks</Counter>
    <Counter>\SQLServer:Databases(*)\Log Truncations</Counter>
    <Counter>\SQLServer:Databases(*)\Percent Log Used</Counter>
    <Counter>\SQLServer:Deprecated Features(*)\Usage</Counter>
    <Counter>\SQLServer:General Statistics\Active Temp Tables</Counter>
    <Counter>\SQLServer:General Statistics\Logins/sec</Counter>
    <Counter>\SQLServer:General Statistics\Logouts/sec</Counter>
    <Counter>\SQLServer:General Statistics\Temp Tables Creation Rate</Counter>
    <Counter>\SQLServer:General Statistics\Temp Tables For Destruction</Counter>
    <Counter>\SQLServer:General Statistics\User Connections</Counter>
    <Counter>\SQLServer:Latches\Latch Waits/sec</Counter>
    <Counter>\SQLServer:Latches\Total Latch Wait Time (ms)</Counter>
    <Counter>\SQLServer:Locks(*)\Average Wait Time (ms)</Counter>
    <Counter>\SQLServer:Locks(*)\Lock Requests/sec</Counter>
    <Counter>\SQLServer:Locks(*)\Lock Timeouts/sec</Counter>
    <Counter>\SQLServer:Locks(*)\Lock Wait Time (ms)</Counter>
    <Counter>\SQLServer:Locks(*)\Lock Waits/sec</Counter>
    <Counter>\SQLServer:Locks(*)\Number of Deadlocks/sec</Counter>
    <Counter>\SQLServer:Memory Manager\Granted Workspace Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Manager\Maximum Workspace Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Manager\Memory Grants Outstanding</Counter>
    <Counter>\SQLServer:Memory Manager\Memory Grants Pending</Counter>
    <Counter>\SQLServer:Memory Manager\Optimizer Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Manager\Stolen Server Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Manager\Target Server Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Manager\Target Server Memory(KB)</Counter>
    <Counter>\SQLServer:Memory Manager\Total Server Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Node(*)\Database Node Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Node(*)\Foreign Node Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Node(*)\Stolen Node Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Node(*)\Target Node Memory (KB)</Counter>
    <Counter>\SQLServer:Memory Node(000)\Total Node Memory (KB)</Counter>
    <Counter>\SQLServer:Plan Cache(*)\Cache Hit Ratio</Counter>
    <Counter>\SQLServer:Resource Pool Stats(*)\CPU usage %</Counter>
    <Counter>\SQLServer:Resource Pool Stats(*)\Max memory (KB)</Counter>
    <Counter>\SQLServer:Resource Pool Stats(*)\Target memory (KB)</Counter>
    <Counter>\SQLServer:Resource Pool Stats(*)\Used memory (KB)</Counter>
    <Counter>\SQLServer:SQL Errors(*)\Errors/sec</Counter>
    <Counter>\SQLServer:SQL Statistics\Auto-Param Attempts/sec</Counter>
    <Counter>\SQLServer:SQL Statistics\Batch Requests/sec</Counter>
    <Counter>\SQLServer:SQL Statistics\Failed Auto-Params/sec</Counter>
    <Counter>\SQLServer:SQL Statistics\Safe Auto-Params/sec</Counter>
    <Counter>\SQLServer:SQL Statistics\SQL Attention rate</Counter>
    <Counter>\SQLServer:SQL Statistics\SQL Compilations/sec</Counter>
    <Counter>\SQLServer:SQL Statistics\SQL Re-Compilations/sec</Counter>
    <Counter>\SQLServer:SQL Statistics\Unsafe Auto-Params/sec</Counter>
    <Counter>\SQLServer:Transactions\Free Space in tempdb (KB)</Counter>
    <Counter>\SQLServer:Transactions\Longest Transaction Running Time</Counter>
    <Counter>\SQLServer:Transactions\NonSnapshot Version Transactions</Counter>
    <Counter>\SQLServer:Transactions\Snapshot Transactions</Counter>
    <Counter>\SQLServer:Transactions\Transactions</Counter>
    <Counter>\SQLServer:Transactions\Version Cleanup rate (KB/s)</Counter>
    <Counter>\SQLServer:Transactions\Version Generation rate (KB/s)</Counter>
    <Counter>\SQLServer:Transactions\Version Store Size (KB)</Counter>
    <Counter>\SQLServer:User Settable(*)\Query</Counter>
    <Counter>\SQLServer:Workload Group Stats(*)\Active parallel threads</Counter>
    <Counter>\SQLServer:Workload Group Stats(*)\Active requests</Counter>
    <Counter>\SQLServer:Workload Group Stats(*)\CPU usage %</Counter>
    <Counter>\SQLServer:Workload Group Stats(*)\Queued requests</Counter>
    <Counter>\SQLServer:Workload Group Stats(*)\Reduced memory grants/sec</Counter>
    <Counter>\SQLServer:Workload Group Stats(*)\Requests completed/sec</Counter>
    <Counter>\SQLServer:Workload Group Stats(*)\Suboptimal plans/sec</Counter>

**Comment by jeffstokes72** [comment]
Ah I see. Ill check that out thanks.

**Comment by clinthuffman** [comment]
Thanks, guys. I have a repro. I'll get this fixed. Sorry!

**Comment by clinthuffman** [comment]
These counter paths must be updated in the SQL Server 2014 threshold file to be fixed. I have contacted the content owner and asked him to update/fix the threshold file.

**Comment by clinthuffman** [comment]
Also, I am working on a new wizard feature that will walk you through collecting performance counters. It will produce a command line (batch), powershell commands (script), and/or a perfmon threshold file depending on what you want. In the meantime, as another work around, consider using the PAL Collector script at http://aka.ms/PalCollector

**Comment by clinthuffman** [comment]
Fixed in 2.8.2, but the content owner still needs to fix the counter paths in the SQL 2014 threshold file.

**Comment by clinthuffman** [comment]
Fixed in 2.8.2, but the content owner still needs to fix the counter paths in the SQL 2014 threshold file.

**Comment by SQLHorizons** [comment]
> ut the content owner still needs to fix the counter paths in the SQL 2014 threshold file.

@clinthuffman has the original owner accepted this task or is it still unassigned?

**Comment by dbaengineer** [comment]
Hi, I am using SQL Server 2014 PAL template (,xml) for SQL Server 2016 SP1. I noticed the following counters not shown after generating .blg file to .htm file thru PAL Wizard (v2.8.2). 

Buffer Lazy Writes per second
PAge reads/sec
free list stalls/sec

I checked template thru PAL editor; these counters are enable however not shown in the report (.htm)

Please share your feedback...

![image](https://user-images.githubusercontent.com/52250365/60212792-12a27680-9830-11e9-8479-e720950b7182.png)
