### ISSUE TITLE
perfmon creating template getting problem

### ISSUE THREAD

**Issue by satyamvv2013** [clinthuffman/PAL#27]
![image](https://user-images.githubusercontent.com/25892644/46126652-ba602900-c24b-11e8-9645-826077e75738.png)
how to resolve this?

**Comment by satyamvv2013** [comment]
Thank you for the response, I found it somewhere in the ggogle and worked it out, its fine now.

If I want to reduce the data columns it is producing, can I delete the tags from the xml ?

Or will it affect the html file which will be created after the analysis.

Thank you

Best regards
[cid:image002.png@01D45712.C5136F00]
Satya
Associate Consultant
Mobile No : 9710476956
Extn: 9090
https://imsva91-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=www.tafe.com&umid=EE6AF778-76E6-FC05-82AC-BE3BBB9485E8&auth=c6cae4180046c553f560dbcbfe34f7a11f00dc0e-119d245f9060521f1c760188aec6b08132556467<https://imsva91-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=http%3a%2f%2fwww.tafe.com&umid=EE6AF778-76E6-FC05-82AC-BE3BBB9485E8&auth=c6cae4180046c553f560dbcbfe34f7a11f00dc0e-44a34554504b3a89dff82bcc0b6a43a5569b6018>

**Comment by clinthuffman** [comment]
Yes, you are welcome to remove as many ANALYSIS nodes as you want. Just select the threshold file and click Edit to modify it. You might have to save it at your Desktop and manually move the file back to the PAL installation folder.

Thank you,

________________________________

**Comment by clinthuffman** [comment]
Fixed in 2.8.2.
