### ISSUE TITLE
PerfMon Templates Don’t Load in Win10

### ISSUE THREAD

**Issue by rmacfadyen** [clinthuffman/PAL#30]
[Better explanation than I could write](https://chentiangemalc.wordpress.com/2015/06/19/performance-analysis-tool-pal-perfmon-templates-dont-load-in-win10/).

The problem appears to be the use of resources in <displayname> and <description> from wdc.dll that no longer exist on win10.

**Comment by jeffstokes72** [comment]
Hey there. This is an old version of PAL you are using. Have you tried the 2.8.2 build on github?

**Comment by jeffstokes72** [comment]
https://github.com/clinthuffman/PAL/blob/master/PAL_FlatFiles_2.8.2.1.zip
@rmacfadyen

**Comment by clinthuffman** [comment]
No further responses, so assuming this was resolved.
