### ISSUE TITLE
PAL Collector Script

### ISSUE THREAD

**Issue by jasonhendrix** [clinthuffman/PAL#31]
Is this still the correct link to get the PAL Collector script?
http://aka.ms/palcollector

I ran that on a few dozen servers, but the files it created reach 500MB within a few minutes.  As this link (https://blogs.technet.microsoft.com/clinth/2013/01/08/pal-collector-script-palcollector-ps1/) indicates, is there still a valid way to automatically create the performance counters that will create approximately 200MB (or 500MB, or any known amount) of data in a 24 hour period?

**Comment by jeffstokes72** [comment]
Hi Jason,

Its a little tricky, because the Process\ area is sized on number of processes, and that's not something the collector would know ahead of time.

Is this like an RDS server or something with a ton of processes running?

**Comment by jeffstokes72** [comment]
Still, that being said, 500MB in a few minutes sounds off...

**Comment by jasonhendrix** [comment]
These are IIS servers running .NET code that communicates with custom COM+ Applications and 3 or 4 custom .NET Windows Services also deployed to the same server.  The only other process running that isn't on by default for Windows Server is security/AV related (Trend Micro).

They are certainly busy servers, but I was hoping to gather 24 hours of stats.  Maybe I should not use Pal Collector and instead manually choose a smaller list of counters?

Thanks for your help!

**Comment by jeffstokes72** [comment]
Yeah I was looking at the dl link you posted. It appears it's collecting the kitchen sink.

What I would do is run the PAL wizard and export the IIS template.
[IIS-PAL.zip](https://github.com/clinthuffman/PAL/files/2600595/IIS-PAL.zip)

**Comment by jeffstokes72** [comment]
or maybe the .NET one. or customize a profile with both .net and iis

**Comment by clinthuffman** [comment]
Sorry, the Maxsize of the script was set to 500 MB. It should have been 100 MB. I fixed it and reposted the zip file back to HTTP://aka.ms/PalCollector. You are welcome to adjust it. Either (1) Download the PalCollector again and reinstall it, (2) change the Max parameter on line 869 of PalCollector.ps1 that you originally downloaded and then reinstall it or (3) make the changes in the PalCollector Performance Monitor data collector properties and then restart the data collector.

**Comment by clinthuffman** [comment]
… and I agree with Jeff, the BLG file shouldn't immediately hit 500 MB unless there is a *lot* of counter instances such as, but not limited to, the Process object. I can look at one of the counter logs to see what is going on. If you want, upload the counter log PalCollector.blg to HTTP://bit.ly/PalUpload. Thank you.

**Comment by jasonhendrix** [comment]
Thanks for your help.  I switched to using the IIS template instead and left the limit at 500 MB.  In a 24 hour period this generated an average of about 430 MB on each of the servers.  So, that works for me.
