### ISSUE TITLE
Test-Property : The term 'Test-Property' is not recognized as the name of a cmdlet, function, script file, or operable

### ISSUE THREAD

**Issue by r2d23k** [clinthuffman/PAL#33]
Hi,

I am getting this error on Win10 x64 PS 5.1, do I need admin rights to run PAL?

Test-Property : The term 'Test-Property' is not recognized as the name of a cmdlet, function, script file, or operable

program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

At C:\Users\xxxx\Documents\WindowsPowerShell\PAL.ps1:157 char:11

+     If ($(Test-Property -InputObject $Error[0] -Name 'CommandInvocati ...

+           ~~~~~~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (Test-Property:String) [], CommandNotFoundException

    + FullyQualifiedErrorId : CommandNotFoundException

Thanks

**Comment by clinthuffman** [comment]
That's odd. That function is used very often in the script. No, you don't need admin rights to run PAL. Can you send the log file from %temp%\PAL.log?

**Comment by clinthuffman** [comment]
Closing due to no response.

**Comment by clinthuffman** [comment]
Reopening per request.

**Comment by r2d23k** [comment]
Hi,
Thanks for re-opening the issue was caused by $ExecutionContext.SessionState.LanguageMode
set to ConstrainedLanguage via system variable and that was populated by GPO.
More details here https://itfordummies.net/2015/06/01/powershell-constrained-mode/

please close this topic and thanks again!
