### ISSUE TITLE
Increase the size of the graphs or make configurable

### ISSUE THREAD

**Issue by wsmelton** [clinthuffman/PAL#4]
As an example, on servers that have multiple drives (e.g. say more than 4 or 5), it can be quite difficult to view the graphs that are generated from the performance counter data. It would be nice if either the graph size was increased to more standard size for monitors in current time, or make it configurable where we can adjust for our installation of PAL.

**Comment by clinthuffman** [comment]
You can change them. Just open PAL.ps1, and adjust the Chart Settings section around line 19.

**Comment by clinthuffman** [comment]
Adjust the Chart Settings in PAL.ps1 and then save the file.

**Comment by wsmelton** [comment]
Thanks. I was just browsing through the files and caught that one.
