### ISSUE TITLE
PAL automation

### ISSUE THREAD

**Issue by SDaniV** [clinthuffman/PAL#40]
Hi Clint,

Is there a way to automate PAL through the command line or in some other way?

Thank you

**Comment by jeffstokes72** [comment]
If you walk through the PAL wizard, the last pane shows you the powershell
command the wizard is running..

**Comment by SDaniV** [comment]
It was right before my eyes :)
Thank you, Jeff!

**Comment by jeffstokes72** [comment]
You bet. I think there's some scripts in a sample dir too, but the core of
it in that UI helps a ton imo.

**Comment by SDaniV** [comment]
Yeah, it looks clear to me now. I'll try to cover it as soon as I can. Thank you for additional advice!
