### ISSUE TITLE
Error: "String was not recognized as a valid DateTime."

### ISSUE THREAD

**Issue by Nifroc** [clinthuffman/PAL#41]
The Perf Mon file was saved as a csv.  It is 4MB large, and was made from a Windows 2016 server. 

Here is the error report:
Overall progress... Status: Creating the HTML report, PAL 2.8.1 Progress: 94%... Creating the HTML report, 

An error occurred on...
$Date1 = Get-Date $([datetime]$global:oPal.aTime[0]) -format $global:sDateTimePattern 
At C:\Program Files\PAL\PAL\PAL.ps1:4701 char:25 + $Date1 = Get-Date $([datetime]$global:oPal.aTime[0]) -format $glo ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Cannot convert value "18:41.5,3526,0,0,0,0,0,0,0,0,0,0,0,0, , , , , ,,," to type "System.DateTime". Error: "String was not recognized as a valid DateTime."

**Comment by jeffstokes72** [comment]
This is likely a localization issue. When locality of Windows are you using?

**Comment by Nifroc** [comment]
I'm running PAL on a Win10 laptop.

**Comment by jeffstokes72** [comment]
Right. So Win10, is it running en-us, or a different languge?

**Comment by Nifroc** [comment]
U.S. English

**Comment by jeffstokes72** [comment]
Ah interersting. You haven't changed the date format in Windows to
something other than default perhaps? I can't repro your issue.

**Comment by Nifroc** [comment]
I haven't changed the date format in Windows.  From the error message, I can tell that it can't define the different columns apart. "Cannot convert value:  "18:41.5,3526,0, . . . " 18:41.5 is the time, 3526 is the second column, and so forth.

**Comment by Nifroc** [comment]
Issue found:  The data collector didn't format the date/time correct.  18:41.5 only shows the time of 12:18:41 AM, without the date.  On my functioning one, the date and time were recorded.  I'll now see why Per Mon didn't record the date field.
