### ISSUE TITLE
Allow a switch (or define natively) that spawned threads only go on odd numbered cores).

### ISSUE THREAD

**Issue by jeffstokes72** [clinthuffman/PAL#5]
Assuming a hyper-threaded host, if each worker thread went on an odd numbered core you'd avoid core 0 (leaving network stack alone, rah rah) plus you'd more effectively use your cache (I think).

OPen to being wrong or being in the weeds here... 🥇 

Jeff

**Comment by clinthuffman** [comment]
Hey Jeffstokes72, it was hard enough for me to "multi-thread" it in the first place. Also, the OS should know best how to schedule threads.

**Comment by jeffstokes72** [comment]
Ok fair enough.
