### ISSUE TITLE
Cannot import Perfmon templates

### ISSUE THREAD

**Issue by twaitsey** [clinthuffman/PAL#53]
Attempting to import a Perfmon template generated using the "Export to Perfmon template file..." button on the Threshold File tab fails by greying out the Next and Finish buttons on the Create new Data Collector Set wizard (see image)
![PAL_Template_not_importing](https://user-images.githubusercontent.com/10653980/66304098-61ae7c00-e8f4-11e9-8468-c298acecd58f.PNG)
 This seems to be caused by the <DisplayName> and <Description>lines in the template XML file, referencing wdc.dll. If those lines are removed (or the XML fields left empty), the import works as expected.

Tested and confirmed as an issue when generating templates on a Windows Server 2016 instance (not tested generation on other instances), and confirmed as an issue importing to Windows Server 2012, 2012R2, 2016, 2016 HyperV and 2019, using the local PerfMon console, and  a remote PerfMon console. (The 2016 HyperV instance doesn't have a local console, so only remote tested)
Tested using the SystemOverview template, and the SQL Server 2014 template, on PAL 2.8.1 

Attached are two XMLs based on the SystemOverview template, one as exported from PAL, and one with manual corrections to make it import. Zipped because Github doesn't like loose XMLs.
[Test XMLs.zip](https://github.com/clinthuffman/PAL/files/3696713/Test.XMLs.zip)

**Comment by clinthuffman** [comment]
Hi twaitsey,

Thank you for reporting this. Have you tried the latest version of PAL, 2.8.2.1? I just tested it on Windows 10 19H1 and I confirmed that the wdc.dll line is not there. I fixed this a few times now and I’m hoping this latest update actually fixes it this time.

Thank you,
Clint Huffman


________________________________

**Comment by twaitsey** [comment]
That looks promising :) 
You might want to make that a release, as it looks like it works

Cheers,
Peter
