### ISSUE TITLE
Cannot pick instance of counter for analysis

### ISSUE THREAD

**Issue by rsasser** [clinthuffman/PAL#6]
The goal is to establish thresholds and baselines for various processes inside the corporation and run them through PAL so that during testing if they exceed the baseline PAL generates warning.  So for example, I want to collect Process/%ProcessorTime(Outlook) and establish a threshold of 10% CPU time, (not inclusive of number of processors - I looked at that code and I can duplicate it, but I cannot get this to run at all)

I use the following code in the threshold:

#// Use PowerShell code to create alerts when the conditions for this threshold are met.
#// Optionally use the variables listed above in the Variables list box.
#// If the condition for this threshold is a static value, then use the StaticThreshold() function.
#// Otherwise, you will need to manually loop through the counter instance collection object.
#// The counter instance collection object has a unique name for each counter data source in this analysis.
#// See the variables in the Variables list box above for more information on the counter instance collection object.

#// Here is a ready to use example on how to use the StaticThreshold() function to define a threshold:
StaticThreshold -CollectionOfCounterInstances $CollectionOfOutlookProcessPercentProcessorTime -Operator 'gt' -Threshold 10

#// The -Operator parameter accepts gt for greater than, ge for greater than or equal to, lt for less than,
#//  and le for less than or equal to. -Threshold is the static value for the threshold.

This crashes with 

Overall progress... Status: Calculating counter statistics [very CPU intensive]..., PAL 2.7.7 Progress: 65%... Calculating counter statistics [very CPU intensive]..., Process Outlook % Processor Time
<BR><BR>
An error occurred on...<BR>        If (@($XmlAnalysis.DATASOURCE).Count -gt 1)
<BR>At C:\Program Files\PAL\PAL\PAL.ps1:1969 char:13
+         If (@($XmlAnalysis.DATASOURCE).Count -gt 1)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<BR>The property 'DATASOURCE' cannot be found on this object. Verify that the property exists.<BR>

**Comment by clinthuffman** [comment]
While PAL was not intended to do specific processes, try the attached file as a working example. Rename the file name to whatever.xml. This example filters on processes with the name Explorer.exe and then inherits from QuickSystemOverview.xml
[SpecificProcesses.txt](https://github.com/clinthuffman/PAL/files/1126258/SpecificProcesses.txt)

**Comment by rsasser** [comment]
Thank you for your quick response.  I apologies for slowness on my side.  The file worked perfectly.  Digging in, the problem comes from something in one of the previous files that isn't in the inheritance file path - in other words, my original code works, if I inherit from one of your files.  At the moment, I'm working around the issue by including your file.

**Comment by clinthuffman** [comment]
Okay, thank you for the confirmation.
