### ISSUE TITLE
 'Process % Processor Time'-  not showing right alert

### ISSUE THREAD

**Issue by SQLRocker** [clinthuffman/PAL#70]
Hi Clint,

I asked a question here, https://docs.microsoft.com/en-us/answers/questions/481562/how-to-convert-39process-processor-time39-value-to.html?childToView=483392#comment-483392 , 

seems like PAL is showing a alert for  'Process % Processor Time' higher than 75% even though it isn't ... Please let me know, thanks.

**Comment by clinthuffman** [comment]
**\Process(*)\% Processor Time** is the sum of CPU time of all of its threads. If a system has 16 CPUs, then it is possible for a single process to consume up to 1600% CPU assuming it has at least 16 threads consuming 100% CPU on all CPUs.

In regards to your question with PAL, I get the number of CPUs on the PC and multiply that value by 75, then I compare it to the \Process(*)\% Processor Time value. If the counter value is greater than the threshold, then it comes up as an alert. 

You can see the code for yourself and even adjust it if you want to. Open PAL, Threshold File tab. Select System Overview as the Title in the drop down menu. Click Edit. The PAL Editor will show the contents of that threshold file. Expand Process and select Process % Processor Time. Go to the Thresholds pane. Select More then 75% of overall processor time usage and click Edit. This shows you the code that calculated the alert.

Also, PAL is just providing the data that Performance Monitor recorded and anomalies can and do happen.

I hope this helps!
