### ISSUE TITLE
processing BLG files takes way too long

### ISSUE THREAD

**Issue by jeffstokes72** [clinthuffman/PAL#8]
Even with max cores used, normal priority, I've been parsing 2 days of a server "System Overview" blg since this morning and I'm about half-way done. Is it more efficient to load parsing in multiple VMs (on the same host) or even just run PAL multiple times with the same resources being shared? I have 24 GB of RAM and a Ryzen 1700x and I'm parsing PAL BLGs at about 8% util.

**Comment by jeffstokes72** [comment]
Actually reality just made a liar out of me. Sometimes it appears to be single PS process based, and the suddenly multiple PS processes spawn. In any event, is there any guidance on faster processing? Should I cap to something besides BLG, or just relog to SQL?

**Comment by cluberti** [comment]
I haven't looked at the code here yet to see how it's being done (as I have a phobia of VB and VB.NET), but I'd wonder if some of the processes could be done in parallel in an MTA powershell.exe process or host?

**Comment by clinthuffman** [comment]
Its the number of counter instances in the counter log that takes the most time to parse mostly from the Process object. Quick System Overview doesn't have it which makes it faster. Beyond that, I don't know.
________________________________

**Comment by jeffstokes72** [comment]
Ah thanks for that tip!
